### ISSUE TITLE
wellicht figure / img/figcaption? 

### ISSUE THREAD

**Issue by TuriGuilano** [lisaoude/exclusive-design#14]
https://github.com/lisaoude/exclusive-design/blob/23bd0e8e192bfb35710afcf1f21bf4b3f6e11cdf/_includes/_partials/_index_omschrijving.html#L28-L31

Ik weet de context niet maar wellicht een optie ipv div?

**Comment by lisaoude** [comment]
Definitely a good idea! We're going to turn this `div` into a `figure`, and the `p` into a `figcaption`
