### ISSUE TITLE
h3 as child of ul

### ISSUE THREAD

**Issue by TuriGuilano** [lisaoude/exclusive-design#16]
https://github.com/lisaoude/exclusive-design/blob/23bd0e8e192bfb35710afcf1f21bf4b3f6e11cdf/_includes/_partials/_minoruitleg.html#L88-L105

Semantics :)

**Comment by lisaoude** [comment]
Good point! We will split this `ul` up into multiple smaller `ul` and turn each `h3` into a `li`
