### ISSUE TITLE
Is your feature / project mobile first?

### ISSUE THREAD

**Issue by TuriGuilano** [lisaoude/exclusive-design#17]
https://github.com/lisaoude/exclusive-design/blob/23bd0e8e192bfb35710afcf1f21bf4b3f6e11cdf/public/styles/overview.css#L144

**Comment by lisaoude** [comment]
Because most of our users will view this website on a larger screen, we've decided to start with the design for the larger screen. For smaller screen only minimal changes will be made, such as a column of articles instead of a row.
