### ISSUE TITLE
I can't get used to headings in link elements...

### ISSUE THREAD

**Issue by joostf** [lisaoude/exclusive-design#26]
https://github.com/lisaoude/exclusive-design/blob/6ef64ce0e987befa4e5729575baca843353e611f/_site/studentenwerk/index.html#L58-L59

**Comment by lisaoude** [comment]
We've decided, in consultation with our coach, to write our code like this.
The reason for this, is because the student work that's being displayed, is a list. Each list item has their own heading and short description.
