### ISSUE TITLE
A section here seems a bit overkill to me..

### ISSUE THREAD

**Issue by joostf** [lisaoude/exclusive-design#27]
https://github.com/lisaoude/exclusive-design/blob/6ef64ce0e987befa4e5729575baca843353e611f/_site/studentenwerk/index.html#L24-L27

**Comment by lisaoude** [comment]
It can look like overkill without having the visual there, but this section is being used as a sticky element at top righthand corner of the screen. Without the section, we can't style it nicely and can't give it it's needed background color.
Also, I don't like 'loose' items such as `h2`, `p` and `a` to just float on the page without a wrapper of some sort.

**Comment by joostf** [comment]
I agree that floating loose elements in the page isn't a good idea. But these elements are wrapped in the header and a div element is more fitting because it's just used for styling purposes imho.
